language: ruby
rvm:
  - 2.2
  - jruby

jobs:
  include:
    - stage: ssh_remote_operations
      script:
        - echo "Installing SSH client..."
        - sudo apt-get install -y ssh sshpass
        - echo "Starting SSH operations..."
        - |
          export SSHPASS=$PIPELINE_SERVER_PASSWORD
          sshpass -e ssh -o StrictHostKeyChecking=root@$PIPELINE_SERVER_IP_ADDRESS << 'ENDSSH'
          echo "Running echo command on remote server..."
          echo "Your command here"
          ENDSSH

stages:
  - name: ssh_remote_operations
    if: type = push